### ISSUE TITLE
Extended validation triggered as fail even returning true

### ISSUE THREAD

**Issue by rained23** [KennedyTedesco/Validation#10]
Hi,

I have some of my validation that use Validator::extend().
I debugged the extended Validator and resulted it return true as it pass the validation.
But using this package, it triggered ->passes() as fail and return message shown my extended validator
message. 

I suspect its happen because some conflict with the package.
When I change back the ValidationServiceProvider back to Laravel, the validation pass.

Using Laravel Validation ServiceProvider
![image](https://cloud.githubusercontent.com/assets/907309/6525286/ca387738-c43e-11e4-80a7-7f63a8eff3da.png)

Using this package Validation ServiceProvider
![image](https://cloud.githubusercontent.com/assets/907309/6525387/f07897ce-c43f-11e4-8243-3cdb0fa480cf.png)

**Comment by rained23** [comment]
This issue only occurred after composer update, so I tried to debug more and the working version for this package is on 3920432a2a6... commit.

Tracing back what was added there, its a PR merged with fix for missing `return` for `parent::_call()` .

So I try to add it to the vendor source code, and its now 

![image](https://cloud.githubusercontent.com/assets/907309/6527631/2633d4fc-c457-11e4-862b-c85d709afcbb.png)

Fixed.

Just some curiosity, because I am on L4 , so the branch I use in composer is `~1.0` as stated in README. But 3920432a2a6... commit tagged as v2.0 . Did using v1 made us lose many bug fix ?

Regards,
Rain

**Comment by KennedyTedesco** [comment]
Hello, @rained23!

Yes, i believe this PR https://github.com/KennedyTedesco/Validation/pull/5 can solve your problem.

I'll create (tomorrow) a new branch for L4 bug fixes, then i'll tag this fix.

:beer:

**Comment by KennedyTedesco** [comment]
@rained23 https://github.com/KennedyTedesco/Validation/tree/v1.2.0

**Comment by rained23** [comment]
Thanks.

:beers:

**Comment by KennedyTedesco** [comment]
No problem. :) Good luck!
