### ISSUE TITLE
Fix illuminate/support and validation versions for L4

### ISSUE THREAD

**Issue by vluzrmos** [KennedyTedesco/Validation#12]
Hello @KennedyTedesco ,

Your package allows the users to install version 1 on Laravel 5, the composer assumes version 1 when run:

`composer require kennedytedesco/validation`

(without the correct version)

You need to fix that:
https://github.com/KennedyTedesco/Validation/blob/v1.2.0/composer.json
```json
 "require-dev": {
        "illuminate/support": ">=4.0.0",
        "illuminate/validation": ">=4.0.0"
    },   
```

to 

```json
 "require-dev": {
        "illuminate/support": "4.*",
        "illuminate/validation": "4.*"
    },   
```

**Comment by KennedyTedesco** [comment]
Done. https://github.com/KennedyTedesco/Validation/pull/13
