### ISSUE TITLE
domain validation return invalid on valid domain

### ISSUE THREAD

**Issue by rained23** [KennedyTedesco/Validation#20]
Hi,

I am using the domain validation rules and it return invalid for .store and probably many more weird TLD domain. I check Respect validation and it return false too, I need to disable the tld check to make it return true. But how do I add the parameters using this package ?

**Comment by rained23** [comment]
Just an update, the latest TLD has been released by Respect/Validation on their master branch 7 days ago, I just alias the latest package from Respect Validation for temporary fix.

**Comment by KennedyTedesco** [comment]
Thanks for reporting. I'm afraid we'll have to wait for a new release of Respect Validation to proper fix this.

**Comment by KennedyTedesco** [comment]
Closing for now.
