### ISSUE TITLE
Melhor usar composer install que composer update

### ISSUE THREAD

**Issue by phabloraylan** [KennedyTedesco/Validation#24]
Nem preciso dizer o porque né?

**Comment by KennedyTedesco** [comment]
Opa, beleza? Se você tem o `composer.json` com as versões bem configuradas, dar o `composer update` em ambiente de **desenvolvimento** não é nenhum problema. O problema é você fazer deploy dando update em produção, ignorando o _composer.lock_.

Mas você tem que razão que essa parte do readme (que tem 6 anos) seria melhor se usasse outra abordagem como, por exemplo:

```
composer require kennedytedesco/validation:^5.0
```

Se você quiser enviar um PR alterando isso, será bem vindo. =D
