### ISSUE TITLE
Validator::extend => Última versão retornando sempre false

### ISSUE THREAD

**Issue by marcelogarbin** [KennedyTedesco/Validation#27]
Cheguei nessa issue https://github.com/KennedyTedesco/Validation/issues/10

@KennedyTedesco estou com o mesmo problema na última versão usando o Laravel 6. O que pode ser, teria algum jeito de contornar isso? O que fiz foi testar com ele instalado e depois removi, parece que realmente está havendo algum conflito. Já estou a algum tempo em cima disso e não consegui evoluir =/

Fiz esse código para testar e sempre retorna false com o seu pacote instalado. Não sei se foi mudado alguma coisa durante as versões...

```php
Validator::extend('video_url', function($attribute, $url, $parameters) {
    return true;
});
```

Parece que quando usado o `Validator::extend` o código é ignorado.

**Comment by KennedyTedesco** [comment]
@marcelogarbin Sabe o que descobri? É que já tem uma regra dessa do Respect:

https://github.com/Respect/Validation/blob/master/library/Rules/VideoUrl.php

Aí ele dá preferência pra usar a regra do Respect, ignorando a sua regra manual.

Se você alterar o nome da sua regra para, por exemplo: "url_video" (invertendo), ele vai funcionar.

**Comment by marcelogarbin** [comment]
Poutz.. pior que nem cheguei a pesquisar nesse outro pacote, falha minha (por isso que as vezes é bom pegar um ar kkkk) :bow:

Fiz o teste aqui e acredito que realmente é isso mesmo, qualquer coisa retorno.

Obrigado @KennedyTedesco pelo help :beers:

**Comment by KennedyTedesco** [comment]
Por nada, meu caro! :blush: :beer:
