### ISSUE TITLE
Mensagem quando cpf esta errado

### ISSUE THREAD

**Issue by RaulCorreia** [KennedyTedesco/Validation#29]
Quando vou exibir a mensagem de erro para o cpf ou cnpj é exibido dessa forma:
validation.cpf

Tentei criar uma regra no arquivo validation.php para informar a mensagem correta mas não consegui, existe alguma forma de criar uma mensagem de validação melhor? como devo criar la no custom?

**Comment by KennedyTedesco** [comment]
Opa, tudo joia? Eu acredito que é só você adicionar uma chave `cpf` lá:

```php
'cpf' => 'Sua mensagem',
```

**Comment by RaulCorreia** [comment]
Você diz na parte custom? por que testei la e nao funcionou, mas irei testar no array principal

**Comment by KennedyTedesco** [comment]
Isso, no array principal. Acredito que deve resolver.

**Comment by RaulCorreia** [comment]
Resolveu sim, muito obrigado.

**Comment by KennedyTedesco** [comment]
Boa! o//
