### ISSUE TITLE
problem with codeception

### ISSUE THREAD

**Issue by p1mps** [KennedyTedesco/Validation#4]
Hello,

I'm using this awesome library and I find it very very useful. However I have an issue with the library and codeception. Codeception seems stupid and it can't find the validators for the custom rules. An example of an error is: 

BadMethodCallException: Method [validateCharset] does not exist.

In the laravel app I don't have this problem anyway, so I think that is codeception the problem indeed. 

I was wondering if anybody here had the same issue and how it's possible to fix it. Thanks in advance

**Comment by diaspar** [comment]
@p1mps did you find a solution for this? I am using the laravel 5 module with codeception and all custom validator methods are giving me the same problem

**Comment by p1mps** [comment]
@diaspar I don't remember exactly how I solved this, take a look on the fork of the project in my account, maybe I patched it in some way
