### ISSUE TITLE
Any chances to have Laravel 5 Available?

### ISSUE THREAD

**Issue by MarlonEtiene** [KennedyTedesco/Validation#8]
Like to use this validation under laravel 5. any chances to have a new version for laravel 5?

**Comment by KennedyTedesco** [comment]
I'll see on the weekend. :+1:

**Comment by herlon214** [comment]
Waiting too :+1:

**Comment by KennedyTedesco** [comment]
@MarlonEtiene  @herlon214 Done guys! :smile: 

Just use:

```
"kennedytedesco/validation": "~2.0"
```

**Comment by herlon214** [comment]
Thanks @KennedyTedesco  :smiley:

**Comment by MarlonEtiene** [comment]
I'll go try. Thanks!
